"""
make_tables.py -- regenerate the result tables from repository outputs.

Reads whatever evaluation/results/ contains and renders it as Markdown.
Nothing is hardcoded: every figure comes from a file produced by
evaluate.py or translate_eval.py in this repository. If a run has not been
performed, its row is absent rather than filled in.

  Table 4 (intrinsic)  Morpheme Boundary Precision and Renyi entropy
  Table 3 (extrinsic)  BLEU and chrF++ per tokenization strategy
"""

import argparse
import json
from pathlib import Path

ARM_LABELS = {
    "movoc_tok": "MoVoC-Tok",
    "movoc_vocab": "MoVoC vocabulary",
    "bpe": "BPE",
    "wordpiece": "WordPiece",
    "sp_shared": "SentencePiece (shared)",
}

LANG_LABELS = {"amharic": "Amharic", "tigrinya": "Tigrinya",
               "tigre": "Tigre", "geez": "Ge'ez"}


def intrinsic_table(path: Path) -> str:
    if not path.exists():
        return "_No intrinsic results yet — run `evaluate.py`._\n"
    data = json.load(open(path, encoding="utf-8"))
    alpha = data.get("alpha", 2.0)

    out = [f"### Intrinsic evaluation (alpha = {alpha})", "",
           "| Language | Tokenization | Boundary Precision ↑ | MorphScore ↑ | "
           "Rényi entropy ↓ | Gold words |",
           "|---|---|---|---|---|---|"]
    for row in data.get("results", []):
        lang = LANG_LABELS.get(row["language"], row["language"])
        if "error" in row:
            out.append(f"| {lang} | — | _{row['error']}_ | | | |")
            continue
        for arm in ARM_LABELS:
            if arm not in row:
                continue
            a = row[arm]
            out.append(f"| {lang} | {ARM_LABELS[arm]} | "
                       f"{a['boundary_precision']} | {a['morphscore']} | "
                       f"{a['renyi_entropy']} | {row['gold_words']} |")
    out.append("")
    out.append("Boundary Precision is computed over multi-morphemic gold "
               "words; see `movoc/metrics.py`.")
    return "\n".join(out) + "\n"


def extrinsic_table(results_dir: Path) -> str:
    files = sorted(results_dir.glob("table3_*.json"))
    if not files:
        return ("_No translation results yet — run "
                "`scripts/run_table3.sh`._\n")

    out = ["### Extrinsic evaluation (machine translation)", "",
           "| Language | Tokenization | Direction | BLEU ↑ | chrF++ ↑ | n |",
           "|---|---|---|---|---|---|"]
    for f in files:
        parts = f.stem.split("_")          # table3_<lang>_<strategy>
        lang = LANG_LABELS.get(parts[1], parts[1])
        arm = ARM_LABELS.get("_".join(parts[2:]), "_".join(parts[2:]))
        data = json.load(open(f, encoding="utf-8"))
        for direction, r in data.get("results", {}).items():
            tag = " (zero-shot)" if r.get("zero_shot") else ""
            out.append(f"| {lang} | {arm} | {direction}{tag} | "
                       f"{r['bleu']} | {r['chrf++']} | {r['n']} |")
    return "\n".join(out) + "\n"


def main():
    here = Path(__file__).resolve().parent.parent
    p = argparse.ArgumentParser(description="Regenerate result tables")
    p.add_argument("--results-dir", type=Path,
                   default=here / "evaluation/results")
    p.add_argument("-o", "--out", type=Path,
                   default=here / "evaluation/results/RESULTS.md")
    args = p.parse_args()

    body = "\n".join([
        "# Results",
        "",
        "Generated by `scripts/make_tables.py` from the contents of",
        "`evaluation/results/`. Every figure below was produced by this",
        "repository; nothing is copied from the paper.",
        "",
        intrinsic_table(args.results_dir / "intrinsic_eval.json"),
        "",
        extrinsic_table(args.results_dir),
    ])
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(body, encoding="utf-8")
    print(body)
    print(f"\nwritten to {args.out}")


if __name__ == "__main__":
    main()
